version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    target-branch: "master"
    schedule:
      interval: monthly
      time: "03:10"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: monthly
      time: "03:00"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
